### ISSUE TITLE
Unable to upload .MP4 file as input

### ISSUE THREAD

**Issue by Alibohra** [mthane/IMBA#3]

**Comment by mthane** [comment]
Hello Alibohra, can you please send me the error message and I can see how I can fix the Issue. Best, Michael

**Comment by Alibohra** [comment]
![image](https://github.com/mthane/IMBA/assets/33547850/e0e4f8fd-6ddb-4bf0-9c4d-219a3116ee0f)

Hi Michael, Unable to select .MP4 file from dropdown menu. Best Ali

**Comment by mthane** [comment]
The tracker was initially designed for uploading a whole folder. Try to click open and then a table with the mp4s should appear. Then you can see the videos in the software. We did not test the software for MAC yet, so I suggest to use Ubuntu 18.03

**Comment by Alibohra** [comment]
Great. Thanks!
I will try it and update you on this.
